# Generated by Django 4.2.7 on 2026-04-13 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('crime_type', models.CharField(choices=[('THEFT', 'Theft'), ('ROBBERY', 'Robbery'), ('ASSAULT', 'Assault'), ('MURDER', 'Murder'), ('KIDNAPPING', 'Kidnapping'), ('CYBERCRIME', 'Cybercrime'), ('FRAUD', 'Fraud'), ('VANDALISM', 'Vandalism'), ('DOMESTIC_VIOLENCE', 'Domestic Violence'), ('DRUG_OFFENSE', 'Drug Offense'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('incident_date', models.DateTimeField()),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('FILED', 'Filed'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('EVIDENCE_COLLECTED', 'Evidence Collected'), ('SUSPECT_IDENTIFIED', 'Suspect Identified'), ('CASE_CLOSED', 'Case Closed'), ('REJECTED', 'Rejected')], default='FILED', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('witness_count', models.IntegerField(default=0)),
                ('suspect_description', models.TextField(blank=True)),
                ('ai_predicted_category', models.CharField(blank=True, max_length=20)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_officer', models.ForeignKey(blank=True, limit_choices_to={'role': 'POLICE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_crimes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Crimes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='suspects/')),
                ('face_encoding', models.JSONField(blank=True, null=True)),
                ('age_estimate', models.IntegerField(blank=True, null=True)),
                ('height_estimate', models.CharField(blank=True, max_length=20)),
                ('identifying_marks', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspects', to='crimes.crime')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document'), ('AUDIO', 'Audio'), ('OTHER', 'Other')], max_length=10)),
                ('file', models.FileField(upload_to='evidence/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('faces_detected', models.IntegerField(default=0)),
                ('face_encodings', models.JSONField(blank=True, null=True)),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='crimes.crime')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Evidence',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='crimes.crime')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
